version: 2
jobs:
  deploy:
    steps:
      - add_ssh_keys:
        fingerprints:
          - "37:4b:6a:f7:8f:40:89:5b:bb:ca:40:53:98:3e:7c:96"
      - run:
          name: Deploy Over SSH
          command: |
             ssh laub@cbtwines.co "sh dev/reploy.sh"
        
        